language: c
sudo: required
matrix:
    include:
        - os: linux
          arch: arm64
          compiler: gcc
          dist: xenial
        - os: linux
          arch: amd64
          compiler: gcc
          dist: xenial
script:
 - ./build_and_test.sh

